options:
  logging: CLOUD_LOGGING_ONLY

logsBucket: gs://bucket--docker-images-loh333678

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/spring-cloud-app-344441/my-docker-repo/spring-boot-app:$SHORT_SHA', '.']

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/spring-cloud-app-344441/my-docker-repo/spring-boot-app:$SHORT_SHA']

images:
  - 'us-central1-docker.pkg.dev/spring-cloud-app-344441/my-docker-repo/spring-boot-app:$SHORT_SHA'
