logsBucket: gs://bucket--docker-images-loh333678

steps:
  # Step 1: Build the JAR file using Gradle
  - name: 'gradle:7.6-jdk17'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gradle build
    id: gradle-build

  # Step 2: Build the Docker image and tag it
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/spring-cloud-app-344441/my-docker-repo/spring-boot-app:$SHORT_SHA',
      '.'
    ]
    waitFor: ['gradle-build']
    id: docker-build

  # Step 3: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/spring-cloud-app-344441/my-docker-repo/spring-boot-app:$SHORT_SHA'
    ]
    waitFor: ['docker-build']

images:
  - 'us-central1-docker.pkg.dev/spring-cloud-app-344441/my-docker-repo/spring-boot-app:$SHORT_SHA'
