apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: gcp-secret
  namespace: default
spec:
  provider: gcp
  parameters:
    secrets: |
      - projects/spring-cloud-app-344441/secrets/db-password
